version: "3"
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}"
      - "POSTGRES_USER=${DB_USERNAME:-postgres}"
      - "POSTGRES_DB=${DB_NAME:-postgres}"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  api:
    build: ./packages/backend
    depends_on:
      - database
    environment:
      # Use env variables or if not set, use default values
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - KOA_PORT=${KOA_PORT:-4000}
    expose:
      - ${KOA_PORT:-4000}
  frontend:
    build: ./packages/frontend
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
